// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8XebGCX6sRZ3wSzS7PcTzKl-SMNNXFrg',
    appId: '1:308244867903:web:9419fdf27ddd1cad09c18a',
    messagingSenderId: '308244867903',
    projectId: 'my-project-1479543973833',
    authDomain: 'my-project-1479543973833.firebaseapp.com',
    databaseURL: 'https://my-project-1479543973833.firebaseio.com',
    storageBucket: 'my-project-1479543973833.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDMoyAmUBRLd_MqIkeTslhjUxaK__3V9M',
    appId: '1:308244867903:android:d94701c0adf60d6009c18a',
    messagingSenderId: '308244867903',
    projectId: 'my-project-1479543973833',
    databaseURL: 'https://my-project-1479543973833.firebaseio.com',
    storageBucket: 'my-project-1479543973833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKonD2knWIpRd0PBK6xpFS-OT9lS3pSZM',
    appId: '1:308244867903:ios:41561b49f807f21b09c18a',
    messagingSenderId: '308244867903',
    projectId: 'my-project-1479543973833',
    databaseURL: 'https://my-project-1479543973833.firebaseio.com',
    storageBucket: 'my-project-1479543973833.appspot.com',
    androidClientId: '308244867903-0g5o2148k0v52a90687sarq7hdknlpjs.apps.googleusercontent.com',
    iosClientId: '308244867903-f4cgjoqcsd5sutcdtvhe3q1bk27f42ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteExampleMy',
  );
}
